Repository openshift/cluster-svcat-controller-manager-operator, pull requests merged in 2019-04, with the labels that each got.

#31 failure to upgrade
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
Labels: approved, lgtm, size/L

#35 Add node-selector annotation to namespace
  bindata/v3.11.0/openshift-svcat-controller-manager/ns.yaml
  manifests/00_namespace.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#34 cleanup
  pkg/operator/generic_client.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_controllermanager_v311_00.go
  pkg/operator/sync_controllermanager_v311_00_test.go
Labels: approved, lgtm, size/M

#33 Build with go1.11
  .travis.yml
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS
