Repository openshift/cluster-svcat-controller-manager-operator, pull requests merged in 2019-05, with the labels that each got.

#38 Fix tolerations
  manifests/09_deployment.yaml
Labels: approved, lgtm, size/S

#39 Bug 1707072: add terminationMessagePolicy FallbackToLogsOnError
  bindata/v3.11.0/openshift-svcat-controller-manager/ds.yaml
  manifests/09_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#40 revamp README
  README.md
Labels: approved, lgtm

#41 Add shawn-hurley to owners file
  OWNERS
Labels: approved, lgtm, size/XS
