Repository openshift/cluster-svcat-controller-manager-operator, pull requests merged in 2019-11, with the labels that each got.

#56 add gauge showing when svcat is enabled
  manifests/0000_90_cluster-svcat-controller-manager-operator_02_servicemonitor.yaml
  pkg/metrics/metrics.go
  pkg/operator/operator.go
  pkg/version/version.go
Labels: approved, lgtm, size/M

#57 Add the version option do display its commit info
  Makefile
  cmd/cluster-svcat-controller-manager-operator/main.go
  pkg/version/version.go
Labels: approved, lgtm, size/S

#59 Bug 1769601: Register with the legacyregistry for metrics
  pkg/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#61 Bug 1744462: set Upgradeable value and other messages
  pkg/operator/operator.go
  pkg/operator/sync_controllermanager_v311_00.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#62 Bug 1770108: remove the old config.crd, fix explain
  manifests/02_config.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#63 Bug 1744462: Set upgradeable condition to true
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
